### PR TITLE
Add protobuf compiler as missing linux dependency

### PR DESCRIPTION
**Pull request by tennox**
It's mentioned below as "If you only work on protobuf", so you definitely need it when you compile the app. (tried without)

### CODE REVIEW

**Comment by tennox** [comment]
I'm actually not sure if it would've be fixed by running `cargo make flowy_dev`

**Comment by MikeWallaceDev** [comment]
Hi @tennox , I run Manjaro, and I don't have the protobuf compiler installed.  In fact, I was not able to install a _working_ protobuf compiler _for Rust_ on Manjaro. I assure you that you can compile and run the application without pb.

**Review by MikeWallaceDev — CHANGES_REQUESTED** [review]
Unless something changed, this protobuf-compiler does not work with Rust. The application name, and parameters are different. 
You'll have to show me that this command actually works, with both Ubuntu, and with Arch.

**Comment by MikeWallaceDev** [comment]
@tennox , so.... It turns out that things have changed! We will soon be removing the generated protobuf files from the repo, and protobuf compilation will become a mandatory step for devs (just like language generation)

So you will soon see this in the documentation, thanks :)

**Pull request closed without merging**
